#message containg status information about lolos subsystems
int8 rc_signal
float32 voltage
float32 current
int8 captain_leak
int8 esc_leak
int8 prevco_leak
int8 edw_leak
int8 battery1_leak
int8 battery2_leak

#ISB status
int8 time_status
int8 trigger_status
int8 actuators_status
int8 thrusters_status
int8 vertical_thrusters_status
int8 usbl_status
int8 scientist_status
int8 edw_status
int8 battery1_status
int8 battery2_status

#Aux outputs
int8 aux_output
int8 servo1_output
int8 servo2_output
int8 lumen_output
int8 mbes_output

string emergency_status
string control_mode
string control_source

int8 thrusters_enabled
int8 vertical_thrusters_enabled

int8 edw_armed
int8 edw_timer_armed
int32 edw_timer_time_left